name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Hugo
      run: |
        curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.112.4/hugo_extended_0.112.4_linux-amd64.tar.gz'
        tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo

    - name: Build
      run: ${RUNNER_TEMP}/hugo

    - name: Create built-site directory
      run: mkdir -p ${GITHUB_WORKSPACE}/built-site

    - name: Copy files to built-site directory
      run: cp -R public/* ${GITHUB_WORKSPACE}/built-site/

    - name: Navigate to built-site directory
      run: cd ${GITHUB_WORKSPACE}/built-site

    - name: Initialize Git
      run: git init

    - name: Add Git remote
      run: git remote add origin https://github.com/dynuchu/blog.git

    - name: Set Git user
      run: |
        git config user.name 'dynuchu'
        git config user.email 'dynuchu@gmail.com'

    - name: Add changes to Git
      run: git add .

    - name: Commit changes
      run: git commit -m 'Updated site'

    - name: Push changes to gh-pages branch
      run: git push --force --set-upstream origin gh-pages
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
